<?php $this->layout("_layout.phtml") ?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.js"></script>
<script>
    angular.module("myApp", []).controller("myCtrl", function ($scope, $http) {
        $scope.form = {};
        $scope.submit = function () {
            if (Number($scope.form.human) == 5){
                var sUrl = "<?php echo $this->urlFor("mailer"); ?>";
                $http.post(sUrl, $scope.form).success(function(data){
                    alert("it worked " + data);
                }).error(function(data){
                    alert("it failed " + data);
                });
            }
            else{
                alert("Sorry wrong answer");  
            } 
        };

    });
</script>
<h1 class="page-header text-center">Contact Form Example</h1>
<form class="form-horizontal" role="form" ng-app="myApp" ng-controller="myCtrl" ng-submit="submit()">
	<div class="form-group">
		<label for="name" class="col-sm-2 control-label">Name</label>
		<div class="col-sm-10">
			<input type="text" class="form-control" id="name" name="name" placeholder="First & Last Name" ng-model="form.name" required>
			<?php //echo "<p class='text-danger'>$errName</p>";?>
		</div>
	</div>
	<div class="form-group">
		<label for="email" class="col-sm-2 control-label">Email</label>
		<div class="col-sm-10">
			<input type="email" class="form-control" id="email" name="email" placeholder="example@domain.com" ng-model="form.email" required>
			<?php //echo "<p class='text-danger'>$errEmail</p>";?>
		</div>
	</div>
	<div class="form-group">
		<label for="message" class="col-sm-2 control-label">Message</label>
		<div class="col-sm-10">
			<textarea class="form-control" rows="4" name="message" ng-model="form.message" required ></textarea>
			<?php //echo "<p class='text-danger'>$errMessage</p>";?>
		</div>
	</div>
	<div class="form-group">
		<label for="human" class="col-sm-2 control-label">2 + 3 = ?</label>
		<div class="col-sm-10">
			<input type="text" class="form-control" id="human" name="human" placeholder="Your Answer" ng-model="form.human" required>
			<?php //echo "<p class='text-danger'>$errHuman</p>";?>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-10 col-sm-offset-2">
			<input id="submit" name="submit" type="submit" value="Send" class="btn btn-primary">
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-10 col-sm-offset-2">
			<?php //echo $result; ?>	
		</div>
	</div>
</form> 
